### ISSUE TITLE
[8.0] account_multicompany_usability : personalización de campos multicompañia según necesidad

### ISSUE THREAD

**Issue by ivantodorovich** [ingadhoc/account-financial-tools#27]
@jjscarafia 
Continuando con la conversación vía email..

Se necesitaría incorporar la posibilidad de funcionalidad agregada por este módulo para el campo **Lista de precios de venta**, ya que sólo nos interesa ver y setear la lista en la compañia consolidadora, y el hecho de ver todas hace más compleja y confusa la vista del cliente.

Sigo sin entender el caso de uso donde interesa setear distintas listas de precios para las distintas compañias hijas. ¿En qué caso deberían ser diferentes? Pero, si en cambio lo que se necesita es que esté seteado en todas por igual, se podría implementar alguna funcionalidad tipo "cascade": si se cambia la lista en la compañia consolidadora, se setea el mismo valor para todas las hijas. O más bien un "mirror", para que si se setea en una hija, también se replique en todas las compañias de ese grupo.

Lo mismo se aplica para: **Posición Fiscal** y **Customer Payment Term**, que son campos cuyos valores no son dependientes a la compañia.

Estoy tirando ideas sin saber cuál es el caso de uso, por eso es que posiblemente esten muy erradas. Sin embargo mi inquietud es la misma: desactivar la nueva funcionalidad en esos campos. Y para esto se me ocurren dos opciones:
- Desglosar este módulo en varios módulos 
  (tal vez con auto_install: True, y que sean desinstalados manualmente si no se lo quiere).
  Podría ser simplemente un módulo nuevo: _account_multicompany_usability_extended_, incorporando la funcionalidad de los 3 campos mencionados arriba.. ya que, a mi parecer van de la mano. El que necesita uno de esos campos, probablemente necesita todos. Y dejar todo el resto en el módulo base.
- Agregar grupos que permitan activar/desactivar la nueva funcionalidad a nivel usuario.
  Lo que no me gusta de esta opción es que la configuración se hace a nivel usuario, y no a nivel sistema. Y esto implica, al menos para mí, más trabajo de mantenimiento.. ya que hay que configurar cada usuario y agrega más posibilidades de errores.

**Comment by jjscarafia** [comment]
Buenas Ivan, esto es un poco viejo. Sigue vigente o hubo cambios que ya lo resolvieron?

**Comment by ivantodorovich** [comment]
Hola Juan!

En nuestro caso lo resolvimos creando nuevas vistas que revierten los cambios realizados por este módulo.. pero supongo que sigue vigente. 

Básicamente lo que hice fue:
- Desactivar esta vista:
  
  ``` html
  <!-- herencia de la vista que agrega la lista de precios,  -->
  <record id="view_pricelist_partner_property_form" model="ir.ui.view">
  ```
- Agregar esta otra vista, revirtiendo los cambios de `view_partner_property_form`, a excepción de los cambios en `property_account_receivable` y `property_account_payable`, que son los únicos que nos interesan:

``` html
<?xml version="1.0"?>
<data>

<!-- fiscal position -->
<field name="property_account_position" position="attributes">
  <attribute name="invisible">0</attribute>
</field>

<xpath expr="//field[@name='property_account_position_ids']/parent::div" position="replace">
</xpath>

<xpath expr="//label[@for='property_account_position_ids']" position="replace">
</xpath>


<!-- payment term -->
<field name="property_payment_term" position="attributes">
   <attribute name="invisible">0</attribute>
</field>

<xpath expr="//field[@name='property_payment_term_ids']/parent::div" position="replace">
</xpath>

<xpath expr="//label[@for='property_payment_term_ids']" position="replace">
</xpath>


<!-- supplier payment term -->
<field name="property_supplier_payment_term" position="attributes">
   <attribute name="invisible">0</attribute>
</field>

<xpath expr="//field[@name='property_supplier_payment_term_ids']/parent::div" position="replace">
</xpath>

<xpath expr="//label[@for='property_supplier_payment_term_ids']" position="replace">
</xpath>

</data>
```
