### ISSUE TITLE
[9.0] Install Base Currency Inverse Rate on Odoo 9 and got error message.

### ISSUE THREAD

**Issue by cewolf2002** [ingadhoc/account-financial-tools#32]
Please let me know how to solve this issue.
Thanks.

http://pastebin.com/8x4weN6h

**Comment by jjscarafia** [comment]
Sorry but we can not replicate the error. Check in our runbot and module is installed ok http://runbot.adhoc.com.ar/runbot/repo/git-github-com-ingadhoc-account-financial-tools-git-7
If you have any other infor please re open the issue
