### ISSUE TITLE
base_currency_inverse_rate bad translation for "rate"

### ISSUE THREAD

**Issue by edser-pcg** [ingadhoc/account-financial-tools#34]
Hello,

Your module works great so far. Just wanted to point out that the translation for rate is "tasa" with an "s" and not "taza" with a "z". It is easy to fix as only is needed to be fixed on the es.po if you're interested. I tried doing the PR myself but I'm not very familiar with GitHub.

Keep up the great work.

**Comment by jjscarafia** [comment]
solved on v9. Thanks for reporting
